"""The migrations must produce exactly the schema the models describe.

Drift between `Base.metadata` and the migration chain is the failure that only
shows up in production, where `create_all` never runs. This test is the cheap
guard: apply every migration to an empty database, then ask Alembic whether the
models would generate any further changes.
"""
from __future__ import annotations

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from app.db.migrate import alembic_config


@pytest.fixture
def sqlite_url(tmp_path):
    return f"sqlite+aiosqlite:///{tmp_path}/migrations.db"


def test_upgrade_downgrade_upgrade_is_clean(sqlite_url):
    config = alembic_config(sqlite_url)
    command.upgrade(config, "head")
    command.downgrade(config, "base")   # a downgrade that fails is a migration you cannot roll back
    command.upgrade(config, "head")


def test_migrations_match_the_models(sqlite_url):
    config = alembic_config(sqlite_url)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - fails only on real drift
        pytest.fail(f"models and migrations have diverged: {exc}")


def test_tables_exist_after_upgrade(sqlite_url, tmp_path):
    import sqlite3

    command.upgrade(alembic_config(sqlite_url), "head")
    con = sqlite3.connect(f"{tmp_path}/migrations.db")
    tables = {row[0] for row in con.execute("select name from sqlite_master where type='table'")}
    assert {
        "users", "refresh_tokens", "portfolios", "positions", "instruments",
        "fund_nav", "daily_close", "macro_events", "rebalance_decisions",
    } <= tables
